// <auto-generated />
namespace Festival.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class clasi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clasi));
        
        string IMigrationMetadata.Id
        {
            get { return "202207220054320_clasi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
